# Generated by Django 4.0.6 on 2022-07-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_home', models.DecimalField(decimal_places=4, max_digits=8)),
                ('distance_last', models.DecimalField(decimal_places=4, max_digits=8)),
                ('value', models.DecimalField(decimal_places=4, max_digits=8)),
                ('same_seller', models.BooleanField()),
                ('physical', models.BooleanField()),
                ('password', models.BooleanField()),
                ('online', models.BooleanField()),
            ],
        ),
    ]
